services:
  postgres:
    image: postgres:14
    container_name: klu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: 0.0.0.0
    ports:
      - '5432:5432'
    volumes:
      - klu-postgres-data:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: ./website
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5173:80'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  klu-postgres-data:
