services:
  postgres:
    image: postgres:14
    container_name: klu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: 0.0.0.0
    ports:
      - '5432:5432'
    volumes:
      - klu-postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./website
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: http://localhost:8000
    ports:
      - '5173:80'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:8000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB: postgres

volumes:
  klu-postgres-data:
